# Generated by Django 2.2.3 on 2019-07-10 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colour',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colour', to='colours.Category'),
        ),
    ]
